const number=value=>Number(value||0);
function cloneStyles(product={}){const styles=JSON.parse(JSON.stringify(product.styles||{}));for(const style of ['flat','twisted']){styles[style]||={colors:{}};styles[style].colors||={};const legacy=product.colors||{};for(const [color,data] of Object.entries(legacy))if(!styles[style].colors[color])styles[style].colors[color]={...data};}return styles;}
function cloneSizes(product={}){return JSON.parse(JSON.stringify(product.sizes||{}));}
const sizeStock=(sizes,stock)=>Object.fromEntries(sizes.map(s=>[s,{stock,available:true}]));
function defaultCatalog(){const colours=['Black','White','Yellow','Baby Pink','Hot Pink','Olive','Teal','Orange','Burgundy','Mustard','Flamingo'];return {version:2,ribbed:{name:'Ribbed Hairbands',description:'Textured ribbed hairbands in everyday and statement shades.',price:10,available:true,colours:Object.fromEntries(colours.map(c=>[c,{stock:20,available:true}])),featured:[{id:'cherry-milk',name:'Cherry Milk',colour:'Pink & White',stock:10,available:true},{id:'navy-milk',name:'Navy Milk',colour:'Blue & White',stock:10,available:true},{id:'noir-gold',name:'Noir Gold',colour:'Black & Gold',stock:10,available:true}]},basics:{tops:[{id:'second-skin-tee',name:'Second Skin Tee',price:70,colours:['Dark Brown'],sizes:sizeStock(['S','M','L','XL','2XL'],2),available:true},{id:'essential-vest-top',name:'Essential Vest Top',price:150,colours:['Black','Coral','White'],sizes:sizeStock(['S','M','L','XL'],3),available:true}],sets:[{id:'second-skin-long-sleeve',name:'Second Skin Long Sleeve',price:200,colours:['White','Blue Black','Nude'],sizes:sizeStock(['S','M','L','XL'],2),available:true},{id:'second-set',name:'Second Set',price:160,colours:['White'],sizes:{},available:true}]}};}
function mergeCatalog(saved={}){const out=defaultCatalog();if(saved.ribbed)out.ribbed={...out.ribbed,...saved.ribbed,colours:{...out.ribbed.colours,...(saved.ribbed.colours||{})},featured:saved.ribbed.featured||out.ribbed.featured};if(saved.basics)for(const group of ['tops','sets']){const map=new Map(out.basics[group].map(p=>[p.id,p]));for(const p of saved.basics[group]||[])map.set(p.id,{...(map.get(p.id)||{}),...p,sizes:{...(map.get(p.id)?.sizes||{}),...(p.sizes||{})}});out.basics[group]=[...map.values()];}return out;}
function styleNeedForStandard(item,style){const mult=Math.max(1,number(item.qty||1));if(item.style==='mixed')return number(item.styleAllocations?.[style]||0)*mult;return item.style===style?number(item.bundlePieces||0)*mult:0;}
function orderUsesSmoothStock(order={}){return (order.items||[]).some(item=>(item.material||'smooth')==='smooth'&&(item.type==='retail'||item.type==='wholesale'));}
function orderUsesApparelStock(order={}){return (order.items||[]).some(item=>item.type==='apparel'&&item.productId==='spandex-tube-top');}
function orderUsesCatalogStock(order={}){return (order.items||[]).some(item=>item.type==='catalog'||(item.type==='wholesale'&&item.material==='ribbed'));}
function orderUsesManagedStock(order={}){return orderUsesSmoothStock(order)||orderUsesApparelStock(order)||orderUsesCatalogStock(order);}
function catalogNode(catalog,key=''){const p=String(key).split('.');if(p[0]==='ribbed'&&p[1]==='colours')return catalog.ribbed?.colours?.[p.slice(2).join('.')];if(p[0]==='ribbed'&&p[1]==='featured')return (catalog.ribbed?.featured||[]).find(x=>x.id===p.slice(2).join('.'));if(p[0]==='basics'){const product=(catalog.basics?.[p[1]]||[]).find(x=>x.id===p[2]);if(p[3]==='sizes')return product?.sizes?.[p.slice(4).join('.')];return product;}return null;}
function applyOrderToStock(order={},smoothProduct={},apparelProduct={},catalogProduct={}){
 const styles=cloneStyles(smoothProduct),sizes=cloneSizes(apparelProduct),catalog=mergeCatalog(catalogProduct),shortages=[],deducted={smooth:{flat:{},twisted:{}},apparel:{sizes:{}},catalog:{}};
 const addSmooth=(style,color,qty)=>{deducted.smooth[style][color]=(deducted.smooth[style][color]||0)+qty};
 const consume=(style,color,qty,label='')=>{qty=number(qty);if(qty<=0||!color)return 0;styles[style]||={colors:{}};styles[style].colors||={};const current=styles[style].colors[color]||{},stock=Math.max(0,number(current.stock)),used=Math.min(stock,qty);styles[style].colors[color]={...current,stock:stock-used};if(used)addSmooth(style,color,used);if(used<qty)shortages.push(`${label||color+' '+style}: needed ${qty}, available ${stock}`);return used;};
 const consumeStandard=(style,qty,label)=>{let remaining=number(qty);if(remaining<=0)return;const candidates=Object.entries(styles[style]?.colors||{}).filter(([,d])=>d?.available!==false&&number(d?.stock)>0).sort((a,b)=>number(b[1]?.stock)-number(a[1]?.stock)||a[0].localeCompare(b[0]));for(const [color] of candidates){if(remaining<=0)break;const current=styles[style].colors[color]||{},stock=Math.max(0,number(current.stock)),used=Math.min(stock,remaining);styles[style].colors[color]={...current,stock:stock-used};if(used)addSmooth(style,color,used);remaining-=used;}if(remaining>0)shortages.push(`${label}: ${remaining} piece${remaining===1?'':'s'} could not be allocated from current stock`);};
 const consumeApparel=(size,qty)=>{size=String(size||'').toUpperCase();qty=Math.max(0,number(qty));if(!size||qty<=0)return;const current=sizes[size]||{},stock=current.available===false?0:Math.max(0,number(current.stock)),used=Math.min(stock,qty);sizes[size]={...current,stock:stock-used};if(used)deducted.apparel.sizes[size]=(deducted.apparel.sizes[size]||0)+used;if(used<qty)shortages.push(`Spandex Tube Top size ${size}: needed ${qty}, available ${stock}`);};
 const consumeCatalog=(key,qty,label)=>{qty=Math.max(0,number(qty));if(!key||qty<=0)return;const node=catalogNode(catalog,key);if(!node){shortages.push(`${label}: inventory record missing`);return;}const stock=node.available===false?0:Math.max(0,number(node.stock??9999)),used=Math.min(stock,qty);if(Number.isFinite(Number(node.stock)))node.stock=stock-used;if(used)deducted.catalog[key]=(deducted.catalog[key]||0)+used;if(used<qty)shortages.push(`${label}: needed ${qty}, available ${stock}`);};
 const consumeRibbedStandard=(qty,label)=>{let remaining=number(qty);const entries=Object.entries(catalog.ribbed?.colours||{}).filter(([,d])=>d?.available!==false&&number(d.stock)>0).sort((a,b)=>number(b[1].stock)-number(a[1].stock));for(const [color] of entries){if(remaining<=0)break;const key=`ribbed.colours.${color}`,stock=number(catalog.ribbed.colours[color].stock),used=Math.min(stock,remaining);catalog.ribbed.colours[color].stock=stock-used;if(used)deducted.catalog[key]=(deducted.catalog[key]||0)+used;remaining-=used;}if(remaining>0)shortages.push(`${label}: ${remaining} pieces could not be allocated from Ribbed stock`);};
 for(const item of order.items||[]){
  if(item.type==='catalog'){consumeCatalog(item.stockKey,number(item.qty),item.name||'Catalog item');continue;}
  if(item.type==='apparel'&&item.productId==='spandex-tube-top'){consumeApparel(item.size,number(item.qty));continue;}
  if(item.type==='wholesale'&&item.material==='ribbed'){const mult=Math.max(1,number(item.qty||1));if(item.wholesaleMode==='custom'&&item.allocations){for(const [color,qty] of Object.entries(item.allocations||{}))consumeCatalog(`ribbed.colours.${color}`,number(qty)*mult,`${color} Ribbed Hairband`);}else consumeRibbedStandard(number(item.bundlePieces||0)*mult,item.name||'Ribbed wholesale');continue;}
  if((item.material||'smooth')!=='smooth')continue;
  if(item.type==='retail')consume(item.style==='twisted'?'twisted':'flat',item.color,number(item.qty),`${item.color} ${item.style||'flat'}`);
  if(item.type==='wholesale'){const mult=Math.max(1,number(item.qty||1));if(item.wholesaleMode==='custom'&&item.allocations){if(item.style==='mixed'){for(const style of ['flat','twisted'])for(const [color,qty] of Object.entries(item.allocations?.[style]||{}))consume(style,color,number(qty)*mult,`${color} ${style}`);}else{const style=item.style==='twisted'?'twisted':'flat';for(const [color,qty] of Object.entries(item.allocations||{}))consume(style,color,number(qty)*mult,`${color} ${style}`);}}else{for(const style of ['flat','twisted']){const need=styleNeedForStandard(item,style);if(need>0)consumeStandard(style,need,`${item.name||'Standard wholesale'} (${style})`);}}}
 }
 return {styles,sizes,catalog,shortages,deducted};
}
function restoreDeductions(smoothProduct={},apparelProduct={},catalogProduct={},deducted={}){const styles=cloneStyles(smoothProduct),sizes=cloneSizes(apparelProduct),catalog=mergeCatalog(catalogProduct);const smooth=deducted.smooth||deducted;for(const style of ['flat','twisted'])for(const [color,qty] of Object.entries(smooth?.[style]||{})){styles[style]||={colors:{}};styles[style].colors||={};const current=styles[style].colors[color]||{};styles[style].colors[color]={...current,stock:Math.max(0,number(current.stock))+Math.max(0,number(qty))};}for(const [size,qty] of Object.entries(deducted.apparel?.sizes||{})){const current=sizes[size]||{};sizes[size]={...current,stock:Math.max(0,number(current.stock))+Math.max(0,number(qty))};}for(const [key,qty] of Object.entries(deducted.catalog||{})){const node=catalogNode(catalog,key);if(node)node.stock=Math.max(0,number(node.stock))+Math.max(0,number(qty));}return {styles,sizes,catalog};}
module.exports={number,defaultCatalog,applyOrderToStock,restoreDeductions,orderUsesManagedStock,orderUsesSmoothStock,orderUsesApparelStock,orderUsesCatalogStock};
