const number=value=>Number(value||0);
function cloneStyles(product={}){const styles=JSON.parse(JSON.stringify(product.styles||{}));for(const style of ['flat','twisted']){styles[style]||={colors:{}};styles[style].colors||={};const legacy=product.colors||{};for(const [color,data] of Object.entries(legacy))if(!styles[style].colors[color])styles[style].colors[color]={...data};}return styles;}
function cloneSizes(product={}){return JSON.parse(JSON.stringify(product.sizes||{}));}
function styleNeedForStandard(item,style){const mult=Math.max(1,number(item.qty||1));if(item.style==='mixed')return number(item.styleAllocations?.[style]||0)*mult;return item.style===style?number(item.bundlePieces||0)*mult:0;}
function orderUsesSmoothStock(order={}){return (order.items||[]).some(item=>(item.material||'smooth')==='smooth'&&(item.type==='retail'||item.type==='wholesale'));}
function orderUsesApparelStock(order={}){return (order.items||[]).some(item=>item.type==='apparel'&&item.productId==='spandex-tube-top');}
function orderUsesManagedStock(order={}){return orderUsesSmoothStock(order)||orderUsesApparelStock(order);}
function applyOrderToStock(order={},smoothProduct={},apparelProduct={}){
 const styles=cloneStyles(smoothProduct),sizes=cloneSizes(apparelProduct),shortages=[],deducted={smooth:{flat:{},twisted:{}},apparel:{sizes:{}}};
 const addSmooth=(style,color,qty)=>{deducted.smooth[style][color]=(deducted.smooth[style][color]||0)+qty};
 const consume=(style,color,qty,label='')=>{qty=number(qty);if(qty<=0||!color)return 0;styles[style]||={colors:{}};styles[style].colors||={};const current=styles[style].colors[color]||{},stock=Math.max(0,number(current.stock)),used=Math.min(stock,qty);styles[style].colors[color]={...current,stock:stock-used};if(used)addSmooth(style,color,used);if(used<qty)shortages.push(`${label||color+' '+style}: needed ${qty}, available ${stock}`);return used;};
 const consumeStandard=(style,qty,label)=>{let remaining=number(qty);if(remaining<=0)return;const candidates=Object.entries(styles[style]?.colors||{}).filter(([,d])=>d?.available!==false&&number(d?.stock)>0).sort((a,b)=>number(b[1]?.stock)-number(a[1]?.stock)||a[0].localeCompare(b[0]));for(const [color] of candidates){if(remaining<=0)break;const current=styles[style].colors[color]||{},stock=Math.max(0,number(current.stock)),used=Math.min(stock,remaining);styles[style].colors[color]={...current,stock:stock-used};if(used)addSmooth(style,color,used);remaining-=used;}if(remaining>0)shortages.push(`${label}: ${remaining} piece${remaining===1?'':'s'} could not be allocated from current stock`);};
 const consumeApparel=(size,qty)=>{size=String(size||'').toUpperCase();qty=Math.max(0,number(qty));if(!size||qty<=0)return;const current=sizes[size]||{},stock=current.available===false?0:Math.max(0,number(current.stock)),used=Math.min(stock,qty);sizes[size]={...current,stock:stock-used};if(used)deducted.apparel.sizes[size]=(deducted.apparel.sizes[size]||0)+used;if(used<qty)shortages.push(`Spandex Tube Top size ${size}: needed ${qty}, available ${stock}`);};
 for(const item of order.items||[]){
  if(item.type==='apparel'&&item.productId==='spandex-tube-top'){consumeApparel(item.size,number(item.qty));continue;}
  if((item.material||'smooth')!=='smooth')continue;
  if(item.type==='retail')consume(item.style==='twisted'?'twisted':'flat',item.color,number(item.qty),`${item.color} ${item.style||'flat'}`);
  if(item.type==='wholesale'){const mult=Math.max(1,number(item.qty||1));if(item.wholesaleMode==='custom'&&item.allocations){if(item.style==='mixed'){for(const style of ['flat','twisted'])for(const [color,qty] of Object.entries(item.allocations?.[style]||{}))consume(style,color,number(qty)*mult,`${color} ${style}`);}else{const style=item.style==='twisted'?'twisted':'flat';for(const [color,qty] of Object.entries(item.allocations||{}))consume(style,color,number(qty)*mult,`${color} ${style}`);}}else{for(const style of ['flat','twisted']){const need=styleNeedForStandard(item,style);if(need>0)consumeStandard(style,need,`${item.name||'Standard wholesale'} (${style})`);}}}
 }
 return {styles,sizes,shortages,deducted};
}
function restoreDeductions(smoothProduct={},apparelProduct={},deducted={}){const styles=cloneStyles(smoothProduct),sizes=cloneSizes(apparelProduct);const smooth=deducted.smooth||deducted;for(const style of ['flat','twisted'])for(const [color,qty] of Object.entries(smooth?.[style]||{})){styles[style]||={colors:{}};styles[style].colors||={};const current=styles[style].colors[color]||{};styles[style].colors[color]={...current,stock:Math.max(0,number(current.stock))+Math.max(0,number(qty))};}for(const [size,qty] of Object.entries(deducted.apparel?.sizes||{})){const current=sizes[size]||{};sizes[size]={...current,stock:Math.max(0,number(current.stock))+Math.max(0,number(qty))};}return {styles,sizes};}
module.exports={number,applyOrderToStock,restoreDeductions,orderUsesManagedStock,orderUsesSmoothStock,orderUsesApparelStock};