async function initCategoryPage(){
  const [items,settings,categories]=await Promise.all([BFCatalog.load(),BFStore.getDoc('settings/store',{}),BFCatalog.loadCategories()]);
  const category=window.BF_CATEGORY;if(!categories.some(c=>c.id===category&&c.visible!==false)){location.href='shop.html';return;}document.querySelector(`[data-cat="${category}"]`)?.classList.add('active');
  const hero=document.querySelector('[data-category-hero]');if(hero){const path=hero.dataset.categoryHero.split('.').reduce((o,k)=>o?.[k],window.BF_IMAGES);if(path)hero.style.backgroundImage=`url("${path}")`;}
  const list=items.filter(x=>x.category===category).sort((a,b)=>(a.featuredOrder??99)-(b.featuredOrder??99));const expanded=category==='ribbed'?list:BFCatalog.expandVariants(list);const grid=document.getElementById('categoryGrid');if(!grid)return;
  const ribbedHex={'Black':'#111111','White':'#ffffff','Yellow':'#f2cf37','Baby Pink':'#f7c9d8','Hot Pink':'#f2388a','Chartreuse':'#8fb339','Green':'#2e7d32','Teal':'#017f7c','Royal Blue':'#2852af','Orange':'#ed7b2f','Burgundy':'#7f2037','Caramel':'#c68642','Flamingo':'#f26f82'};
  let ribbedStyle=new URLSearchParams(location.search).get('style')==='twisted'?'twisted':'flat';const ribbedVariant=item=>BFCatalog.variant(item,ribbedStyle);
  const render=()=>{
    if(category==='ribbed'){document.querySelectorAll('[data-ribbed-style]').forEach(b=>b.classList.toggle('active',b.dataset.ribbedStyle===ribbedStyle));const intro=document.getElementById('ribbedStyleIntro');if(intro)intro.textContent=ribbedStyle==='flat'?'Classic flat ribbed bands in every available shade.':'Twisted-front ribbed bands with texture and a sculpted centre.';}
    grid.innerHTML=expanded.map(item=>{
      const master=item.masterProductId?list.find(x=>x.id===item.masterProductId)||item:item,variant=category==='ribbed'?ribbedVariant(item):item,preorder=BFCatalog.isPreorder(master),available=category==='ribbed'?variant.available!==false&&(preorder||Number(variant.stock??0)>0):BFCatalog.purchasable(master,item.variantId||'',''),price=BFCatalog.price(master,settings),compareAt=BFCatalog.compareAtPrice(master,settings),url=master.id==='spandex-tube-top'&&!item.variantId?'tube-top.html':`item.html?id=${encodeURIComponent(master.id)}${category==='ribbed'?`&style=${ribbedStyle}`:item.variantId?`&variant=${encodeURIComponent(item.variantId)}`:''}`,swatch=category==='ribbed'&&ribbedHex[master.color]?`<i class="ribbed-swatch" style="background:${ribbedHex[master.color]}" aria-hidden="true"></i>`:'',image=(()=>{const direct=category==='ribbed'?BFCatalog.image(master,ribbedStyle):BFCatalog.image(master,'flat',item.variantId);return direct&&direct!=='images/placeholder-product.svg'?direct:BFCatalog.fallbackImage(item,expanded,categories);})(),title=category==='ribbed'?`${ribbedStyle==='twisted'?'Twisted':'Flat'} ${master.name.replace(/^(Flat |Twisted )?/,'')}`:master.name,badges=[master.featuredOrder<=3&&category==='ribbed'?'Print Collection':'',preorder?'Pre-order':''].filter(Boolean).map(t=>`<span class="catalog-tile-badge${t==='Pre-order'?' preorder':''}">${t}</span>`).join(''),quickAdd=category==='ribbed'&&available?`<button class="catalog-quick-add" data-quick-add type="button">Add to Bag</button>`:'';return `<article class="catalog-tile"><a href="${url}"><div class="catalog-tile-media"><img src="${image}" alt="${escCat(title)}" loading="lazy">${badges}<span class="catalog-status ${preorder?'preorder':''}">${preorder?'Pre-order':available?'Available':'Sold out'}</span>${quickAdd}</div><div class="catalog-tile-copy"><h3>${escCat(title)}</h3><p>${escCat(item.color||master.subtitle||master.color||'')}${swatch}</p><strong>${available&&price?BFCatalog.priceHtml(price,compareAt):preorder?'Pre-order':available?'Price available soon':'Sold out'}</strong>${preorder&&BFCatalog.preorderDate(master)?`<small class="catalog-fulfilment-date">Fulfilment from ${window.BFFulfilment?.shortDate?.(BFCatalog.preorderDate(master))||BFCatalog.preorderDate(master)}</small>`:''}</div></a></article>`;
    }).join('')||'<p>No products are available in this collection yet.</p>';
    if(category==='ribbed')grid.querySelectorAll('[data-quick-add]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const card=btn.closest('.catalog-tile');const link=card?.querySelector('a');const href=link?new URL(link.href,location.href):null;const style=href?.searchParams.get('style')==='twisted'?'twisted':'flat';const itemId=href?.searchParams.get('id');const product=list.find(x=>x.id===itemId)||list.find(x=>x.category==='ribbed'&&String(x.name||'').toLowerCase().includes(String(card?.querySelector('h3')?.textContent||'').toLowerCase().replace(/^flat |^twisted /,'')));const variant=product?ribbedVariant(product,style):null;if(!product||!variant||variant.available===false)return;BF.addCatalogProduct(product,'',Number(product.price||BFCatalog.price(product,settings)),BFCatalog.image(product,style),1,style,'');}));
  };
  if(category==='ribbed')document.querySelectorAll('[data-ribbed-style]').forEach(btn=>btn.onclick=()=>{ribbedStyle=btn.dataset.ribbedStyle==='twisted'?'twisted':'flat';history.replaceState(null,'',`${location.pathname}?style=${ribbedStyle}`);render();});
  render();
}
function escCat(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
document.addEventListener('DOMContentLoaded',initCategoryPage);
