async function initCategoryPage(){
  const [items,settings]=await Promise.all([BFCatalog.load(),BFStore.getDoc('settings/store',{})]);
  const category=window.BF_CATEGORY;document.querySelector(`[data-cat="${category}"]`)?.classList.add('active');
  const hero=document.querySelector('[data-category-hero]');if(hero){const path=hero.dataset.categoryHero.split('.').reduce((o,k)=>o?.[k],window.BF_IMAGES);if(path)hero.style.backgroundImage=`url("${path}")`}
  const list=items.filter(x=>x.category===category).sort((a,b)=>(a.featuredOrder??99)-(b.featuredOrder??99));
  const grid=document.getElementById('categoryGrid');if(!grid)return;
  grid.innerHTML=list.map(item=>{const price=BFCatalog.price(item,settings),available=item.available!==false&&(item.sizes?Object.values(item.sizes).some(s=>s.available!==false&&Number(s.stock)>0):Number(item.stock??1)>0),url=item.id==='spandex-tube-top'?'tube-top.html':`item.html?id=${encodeURIComponent(item.id)}`;return `<article class="catalog-tile"><a href="${url}"><div class="catalog-tile-media"><img src="${BFCatalog.image(item)}" alt="${item.name}" loading="lazy">${item.featuredOrder<=3&&category==='ribbed'?'<span class="catalog-tile-badge">Print Collection</span>':''}${category==='ribbed'?`<button class="catalog-quick-add" type="button" ${available?'':'disabled'} aria-label="Add ${item.name} to bag" data-quick-add="${item.id}"><i class="fa-solid fa-bag-shopping"></i></button>`:''}</div><div class="catalog-tile-copy"><h3>${item.name}</h3><p>${item.subtitle||item.color||''}</p><strong>${available?(price?BF.money(price):'Price available soon'):'Sold out'}</strong></div></a></article>`}).join('')||'<p>No products are available in this collection yet.</p>';
  if(category==='ribbed')grid.querySelectorAll('[data-quick-add]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const item=list.find(x=>x.id===btn.dataset.quickAdd);if(!item)return;const stock=BFCatalog.stock(item);if(stock<=0)return BF.toast('This hairband is currently sold out.');BF.addCatalogProduct(item,'',BFCatalog.price(item,settings),BFCatalog.image(item),1)}));
}
document.addEventListener('DOMContentLoaded',initCategoryPage);
