let dynamicCollectionItems=[],dynamicCollectionSettings={},dynamicCategory=null,dynamicCategories=[];
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function expandedCollectionItems(items){return BFCatalog.expandVariants(items);}
function renderDynamicCollection(){
  const grid=document.getElementById('collectionGrid'),empty=document.getElementById('collectionEmpty');if(!grid||!empty)return;let list=expandedCollectionItems(dynamicCollectionItems),sort=document.getElementById('collectionSort')?.value||'featured';
  if(sort==='name')list.sort((a,b)=>String(a.name).localeCompare(String(b.name))||String(a.color||'').localeCompare(String(b.color||'')));
  else if(sort==='low')list.sort((a,b)=>BFCatalog.price(a,dynamicCollectionSettings)-BFCatalog.price(b,dynamicCollectionSettings));
  else if(sort==='high')list.sort((a,b)=>BFCatalog.price(b,dynamicCollectionSettings)-BFCatalog.price(a,dynamicCollectionSettings));
  else list.sort((a,b)=>Number(a.featuredOrder||99)-Number(b.featuredOrder||99)||String(a.name||'').localeCompare(String(b.name||'')));
  document.getElementById('collectionCount').textContent=`${list.length} product${list.length===1?'':'s'}`;empty.hidden=!!list.length;
  grid.innerHTML=list.map(item=>{const preorder=BFCatalog.isPreorder(item),available=BFCatalog.purchasable(item,item.variantId,''),price=BFCatalog.price(item,dynamicCollectionSettings),compareAt=BFCatalog.compareAtPrice(item,dynamicCollectionSettings),url=`item.html?id=${encodeURIComponent(item.masterProductId||item.id)}${item.variantId?`&variant=${encodeURIComponent(item.variantId)}`:''}`,badge=preorder?'Pre-order':available?'Available':'Sold out',statusClass=preorder?' preorder':available?'':' is-unavailable';const image=BFCatalog.image(item,'flat',item.variantId)||BFCatalog.fallbackImage(item,dynamicCollectionItems,dynamicCategories);return `<a class="catalog-tile${statusClass}" href="${url}"><div class="catalog-tile-media"><img src="${esc(image)}" alt="${esc(item.name)}" loading="lazy"><span class="catalog-status ${preorder?'preorder':''}">${badge}</span></div><div class="catalog-tile-copy"><h3>${esc(item.name)}</h3><p>${esc(item.color||item.subtitle||dynamicCategory.name)}</p><strong>${price?BFCatalog.priceHtml(price,compareAt):'View product'}</strong>${preorder&&BFCatalog.preorderDate(item)?`<small class="catalog-fulfilment-date">Fulfilment from ${esc(window.BFFulfilment?.shortDate?.(BFCatalog.preorderDate(item))||BFCatalog.preorderDate(item))}</small>`:''}</div></a>`}).join('');
}
async function initDynamicCollection(){const id=new URLSearchParams(location.search).get('category')||'';const [categories,items,settings]=await Promise.all([BFCatalog.loadCategories(),BFCatalog.load(),BFStore.getDoc('settings/store',{})]);dynamicCategories=categories;dynamicCategory=categories.find(c=>c.id===id&&c.visible!==false);if(!dynamicCategory){location.href='shop.html';return;}dynamicCollectionItems=items.filter(x=>x.category===id);dynamicCollectionSettings=settings;const title=`${dynamicCategory.name} | Band Factory Ghana`,desc=(dynamicCategory.description||`Shop the ${dynamicCategory.name} collection from Band Factory Ghana. Browse current products, prices and availability.`).slice(0,165),fallback=(dynamicCategory.image||BFCatalog.fallbackImage(dynamicCollectionItems[0]||{},dynamicCollectionItems,categories)),image=new URL(fallback,'https://bandfactory.store/').href;document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',desc);document.querySelector('link[rel="canonical"]')?.setAttribute('href',`https://bandfactory.store/collection.html?category=${encodeURIComponent(dynamicCategory.id)}`);[['meta[property="og:title"]',title],['meta[property="og:description"]',desc],['meta[property="og:image"]',image],['meta[name="twitter:title"]',title],['meta[name="twitter:description"]',desc],['meta[name="twitter:image"]',image]].forEach(([sel,val])=>document.querySelector(sel)?.setAttribute('content',val));document.getElementById('collectionName').textContent=dynamicCategory.name;document.getElementById('collectionEyebrow').textContent=dynamicCategory.eyebrow||'Band Factory Collection';document.getElementById('collectionDescription').textContent=dynamicCategory.description||'';if(dynamicCategory.image)document.getElementById('collectionHero').style.setProperty('--collection-image',`url("${dynamicCategory.image}")`);document.getElementById('collectionSort').onchange=renderDynamicCollection;renderDynamicCollection();}
document.addEventListener('DOMContentLoaded',initDynamicCollection);
