let dynamicCollectionItems=[],dynamicCollectionSettings={},dynamicCategory=null,dynamicCategories=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function renderDynamicCollection(){
  const grid=document.getElementById('collectionGrid'),empty=document.getElementById('collectionEmpty');if(!grid||!empty)return;
  let list=dynamicCollectionItems.slice();
  const sort=document.getElementById('collectionSort')?.value||'featured';
  if(sort==='name')list.sort((a,b)=>String(a.name).localeCompare(String(b.name)));
  else if(sort==='low')list.sort((a,b)=>BFCatalog.price(a,dynamicCollectionSettings)-BFCatalog.price(b,dynamicCollectionSettings));
  else if(sort==='high')list.sort((a,b)=>BFCatalog.price(b,dynamicCollectionSettings)-BFCatalog.price(a,dynamicCollectionSettings));
  else list.sort((a,b)=>Number(a.featuredOrder||99)-Number(b.featuredOrder||99)||String(a.name||'').localeCompare(String(b.name||'')));
  document.getElementById('collectionCount').textContent=`${list.length} product${list.length===1?'':'s'}`;empty.hidden=!!list.length;
  grid.innerHTML=list.map(product=>{
    const v=BFCatalog.featuredVariant(product),pre=BFCatalog.isPreorder(product),available=BFCatalog.purchasable(product,v?.id||''),price=BFCatalog.price(product,dynamicCollectionSettings),compare=BFCatalog.compareAtPrice(product,dynamicCollectionSettings),img=BFCatalog.variantImage(product,v?.id||'',dynamicCollectionItems,dynamicCategories),url=`item.html?id=${encodeURIComponent(product.id)}${v?.id?`&variant=${encodeURIComponent(v.id)}`:''}`;
    const swatches=BFCatalog.variants(product).length>1?`<div class="bf-card-swatches" aria-label="Choose colour">${BFCatalog.variants(product).map(x=>`<button class="bf-card-swatch${x.id===v?.id?' is-active':''}" type="button" data-card-variant="${esc(x.id)}" title="${esc(x.color)}" aria-label="${esc(x.color)}" aria-pressed="${x.id===v?.id?'true':'false'}"><span style="--swatch:${esc(x.hex||'#ddd')}"></span><small>${esc(x.color)}</small></button>`).join('')}</div>`:'';
    return `<article class="catalog-tile bf-variant-card" data-bf-variant-card data-product-id="${esc(product.id)}"><a class="catalog-tile-link" href="${url}" data-card-link><div class="catalog-tile-media"><img data-card-image src="${esc(img)}" alt="${esc(product.name)}${v?.color?' in '+esc(v.color):''}" loading="lazy">${pre?'<span class="catalog-tile-badge preorder">Pre-order</span>':''}<span class="catalog-status ${pre?'preorder':''}">${pre?'Pre-order':available?'Available':'Sold out'}</span></div><div class="catalog-tile-copy"><h3>${esc(product.name)}</h3><p data-card-colour>${esc(v?.color||product.subtitle||dynamicCategory.name)}</p>${swatches}<strong>${available||pre?BFCatalog.priceHtml(price,compare):'View product'}</strong>${pre&&BFCatalog.preorderDate(product)?`<small class="catalog-fulfilment-date">Fulfilment from ${esc(window.BFFulfilment?.shortDate?.(BFCatalog.preorderDate(product))||BFCatalog.preorderDate(product))}</small>`:''}</div></a></article>`;
  }).join('');
  BFCatalog.bindVariantCards(grid,id=>list.find(x=>x.id===id));
}
async function initDynamicCollection(){const id=new URLSearchParams(location.search).get('category')||'';const [categories,items,settings]=await Promise.all([BFCatalog.loadCategories(),BFCatalog.load(),BFStore.getDoc('settings/store',{})]);dynamicCategories=categories;dynamicCategory=categories.find(c=>c.id===id&&c.visible!==false);if(!dynamicCategory){location.href='shop.html';return;}dynamicCollectionItems=items.filter(x=>x.category===id);dynamicCollectionSettings=settings;const title=`${dynamicCategory.name} | Band Factory Ghana`,desc=(dynamicCategory.description||`Shop the ${dynamicCategory.name} collection from Band Factory Ghana. Browse current products, prices and availability.`).slice(0,165),fallback=(dynamicCategory.image||BFCatalog.fallbackImage(dynamicCollectionItems[0]||{},dynamicCollectionItems,categories)),image=new URL(fallback,'https://bandfactory.store/').href;document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',desc);document.querySelector('link[rel="canonical"]')?.setAttribute('href',`https://bandfactory.store/collection.html?category=${encodeURIComponent(dynamicCategory.id)}`);[['meta[property="og:title"]',title],['meta[property="og:description"]',desc],['meta[property="og:image"]',image],['meta[name="twitter:title"]',title],['meta[name="twitter:description"]',desc],['meta[name="twitter:image"]',image]].forEach(([sel,val])=>document.querySelector(sel)?.setAttribute('content',val));document.getElementById('collectionName').textContent=dynamicCategory.name;document.getElementById('collectionEyebrow').textContent=dynamicCategory.eyebrow||'Band Factory Collection';document.getElementById('collectionDescription').textContent=dynamicCategory.description||'';if(dynamicCategory.image)document.getElementById('collectionHero').style.setProperty('--collection-image',`url("${dynamicCategory.image}")`);document.getElementById('collectionSort').onchange=renderDynamicCollection;renderDynamicCollection();}
document.addEventListener('DOMContentLoaded',initDynamicCollection);