let currentItem=null,currentView=null,currentSettings={},selectedSize='',selectedRibbedStyle='flat',selectedVariantId='',qty=1,allItems=[],allCategories=[];
const $id=id=>document.getElementById(id);
const apparelSizeOrder=['XS','S','M','L','XL','2XL','3XL','4XL','5XL','6XL'];
function esc(v=''){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function sortedSizes(sizes={}){return Object.entries(sizes).sort(([a],[b])=>{const A=String(a).trim().toUpperCase(),B=String(b).trim().toUpperCase(),ai=apparelSizeOrder.indexOf(A),bi=apparelSizeOrder.indexOf(B);return (ai<0?1000:ai)-(bi<0?1000:bi)||A.localeCompare(B,undefined,{numeric:true});});}
function showError(msg=''){const el=$id('itemError');if(!el)return;el.textContent=msg;el.hidden=!msg;}
function hasColorVariants(){return !!currentItem?.variants?.length;}
function activeProduct(){return hasColorVariants()?BFCatalog.variantView(currentItem,selectedVariantId):currentItem||{};}
function itemHasSizes(){return Object.keys(activeProduct()?.sizes||{}).length>0;}
function currentVariant(){if(currentItem?.category==='ribbed'&&!hasColorVariants())return BFCatalog.variant(currentItem,selectedRibbedStyle);if(hasColorVariants())return BFCatalog.variant(currentItem,selectedVariantId);return activeProduct();}
function itemStock(){const p=activeProduct();return BFCatalog.stock(currentItem,selectedSize,hasColorVariants()?selectedVariantId:'');}
function itemIsPreorder(){return !!BFCatalog?.isPreorder?.(currentItem);}
function currentImage(){const direct=BFCatalog.image(currentItem,currentItem?.category==='ribbed'&&!hasColorVariants()?selectedRibbedStyle:'flat',hasColorVariants()?selectedVariantId:'');return direct&&direct!=='images/placeholder-product.svg'?direct:BFCatalog.fallbackImage(currentItem,allItems,allCategories);}
function itemTitle(){if(currentItem?.category==='ribbed'&&!hasColorVariants()){const style=selectedRibbedStyle==='twisted'?'Twisted':'Flat';return `${style} ${String(currentItem.name||'').replace(/^(Flat |Twisted )?/,'')}`;}return hasColorVariants()&&activeProduct().color?`${currentItem.name} · ${activeProduct().color}`:currentItem.name;}
function renderVariantPicker(){const box=$id('itemVariantArea');if(!box)return;if(!hasColorVariants()){box.hidden=true;box.innerHTML='';return;}const variants=BFCatalog.variants(currentItem);box.hidden=false;box.innerHTML=`<div class="option-label"><span>Select a colour</span><small id="selectedVariantLabel">${esc(activeProduct().color||'Choose one to continue')}</small></div><div class="item-variant-grid" role="group" aria-label="Product colours">${variants.map(v=>`<button type="button" class="item-variant-option ${v.id===selectedVariantId?'active':''}" data-variant-id="${esc(v.id)}"><span class="item-variant-thumb">${v.image?`<img src="${esc(v.image)}" alt="">`:'<i class="fa-regular fa-image"></i>'}</span><span>${esc(v.color)}</span></button>`).join('')}</div>`;box.querySelectorAll('[data-variant-id]').forEach(btn=>btn.onclick=()=>{selectedVariantId=btn.dataset.variantId||'';selectedSize='';qty=1;renderItemView();});}
function renderSizePicker(){const area=$id('itemSizeArea'),box=$id('itemSizes');if(!area||!box)return;const sizes=activeProduct()?.sizes||{};if(!Object.keys(sizes).length){area.hidden=true;box.innerHTML='';return;}area.hidden=false;box.innerHTML=sortedSizes(sizes).map(([size,d])=>`<button class="tube-size-btn ${size===selectedSize?'active':''}" data-size="${esc(size)}" ${d.available===false||(!itemIsPreorder()&&Number(d.stock||0)<=0)?'disabled':''}>${esc(size)}</button>`).join('');box.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size||'';qty=1;showError();$id('selectedSizeLabel').textContent=`Selected: ${selectedSize}`;box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));updateBuy();});}
function renderFulfilmentNotice(){const box=$id('itemFulfilmentNotice');if(!box)return;const preorder=itemIsPreorder();if(!preorder){box.hidden=true;box.innerHTML='';return;}const date=window.BFFulfilment?.formatDate?.(BFCatalog.preorderDate(currentItem))||BFCatalog.preorderDate(currentItem)||'the announced date';box.hidden=false;box.innerHTML=`<i class="fa-regular fa-calendar" aria-hidden="true"></i><div><strong>Pre-order</strong><span>This item is not ready for immediate delivery yet. You can pay for it now and we will prepare it for fulfilment from <strong>${esc(date)}</strong>.</span><small>When you add ready-to-ship items to the same bag, checkout will let you choose whether to receive those items first or have everything delivered together.</small></div>`;}
function updateRibbedStyleUI(){if(currentItem?.category!=='ribbed'||hasColorVariants())return;const styleName=selectedRibbedStyle==='twisted'?'Twisted':'Flat',d=currentVariant();$id('itemStyles')?.querySelectorAll('[data-item-style]').forEach(b=>b.classList.toggle('active',b.dataset.itemStyle===selectedRibbedStyle));if($id('selectedStyleLabel'))$id('selectedStyleLabel').textContent=`Selected: ${styleName}`;if($id('itemImage')){$id('itemImage').src=BFCatalog.image(currentItem,selectedRibbedStyle);$id('itemImage').alt=`${styleName} ${currentItem.name}`;}history.replaceState(null,'',`item.html?id=${encodeURIComponent(currentItem.id)}&style=${selectedRibbedStyle}`);if(d.available===false||Number(d.stock??0)<=0)showError(`${styleName} is currently sold out in this colour.`);else showError();}
function renderItemView(){
  currentView=activeProduct();
  const title=itemTitle(),img=currentImage(),preorder=itemIsPreorder(),categoryInfo=allCategories.find(c=>c.id===currentItem.category),p=BFCatalog.price(currentItem,currentSettings),compareAt=BFCatalog.compareAtPrice(currentItem,currentSettings);
  const variantQuery=hasColorVariants()?`&variant=${encodeURIComponent(selectedVariantId)}`:'';
  const seoTitle=`${title} | Band Factory Ghana`,seoDesc=currentItem.description?`${currentItem.description} ${preorder?`Pre-order for fulfilment from ${window.BFFulfilment?.formatDate?.(BFCatalog.preorderDate(currentItem))||BFCatalog.preorderDate(currentItem)}.`:'Shop online from Band Factory Ghana.'}`:`Shop ${title} from Band Factory Ghana.`;const canonical=`https://bandfactory.store/item.html?id=${encodeURIComponent(currentItem.id)}${currentItem.category==='ribbed'?`&style=${selectedRibbedStyle}`:''}${variantQuery}`;
  document.title=seoTitle;document.querySelector('meta[name="description"]')?.setAttribute('content',seoDesc);document.querySelector('link[rel="canonical"]')?.setAttribute('href',canonical);[['og:title',seoTitle],['og:description',seoDesc],['og:url',canonical],['og:image',new URL(img,'https://bandfactory.store/').href]].forEach(([k,v])=>document.querySelector(`meta[property="${k}"]`)?.setAttribute('content',v));[['twitter:title',seoTitle],['twitter:description',seoDesc],['twitter:image',new URL(img,'https://bandfactory.store/').href]].forEach(([k,v])=>document.querySelector(`meta[name="${k}"]`)?.setAttribute('content',v));
  $id('itemName').textContent=title;$id('itemCrumb').textContent=title;$id('itemDescription').textContent=currentItem.description||'';$id('itemDetailsAccordion').textContent=currentItem.description||'';$id('itemImage').src=img;$id('itemImage').alt=title;$id('itemShadeTab').textContent=currentView.color||currentItem.subtitle||currentItem.name;$id('itemCategory').textContent=currentItem.category==='ribbed'?'Ribbed Hairband':(categoryInfo?.name||'Band Factory Collection');
  const saving=$id('itemSavingNote');if(saving){saving.innerHTML=p?BFCatalog.savingsHtml(p,compareAt):'';saving.hidden=!saving.innerHTML;}$id('itemPrice').innerHTML=p?BFCatalog.priceHtml(p,compareAt,'pdp-sale-price'):'Price available soon';
  const features=(currentView.subtitle||currentView.color||'').split('·').map(x=>x.trim()).filter(Boolean).slice(0,4);$id('itemFeatureRow').innerHTML=features.map(x=>`<span>${esc(x)}</span>`).join('');$id('itemPackNote').innerHTML=currentItem.packSize?`<i class="fa-solid fa-layer-group"></i> ${currentItem.packSize}-piece purchase.`:'';
  renderVariantPicker();renderFulfilmentNotice();renderSizePicker();
  const gallery=[img,...(currentView.images||[]),...(currentItem.images||[])].filter((x,i,a)=>x&&a.indexOf(x)===i),galleryBox=$id('itemGallery');if(galleryBox){galleryBox.hidden=gallery.length<=1;if(gallery.length>1)galleryBox.innerHTML=gallery.map((url,i)=>`<button type="button" class="${i===0?'active':''}" data-gallery-image="${esc(url)}"><img src="${esc(url)}" alt="${esc(title)}"></button>`).join('');galleryBox.querySelectorAll('[data-gallery-image]').forEach(btn=>btn.onclick=()=>{$id('itemImage').src=btn.dataset.galleryImage;galleryBox.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===btn));});}
  if(currentItem.category==='ribbed'&&!hasColorVariants()){$id('itemStyleArea').hidden=false;$id('itemStyles').querySelectorAll('[data-item-style]').forEach(b=>b.onclick=()=>{selectedRibbedStyle=b.dataset.itemStyle==='twisted'?'twisted':'flat';qty=1;renderItemView();});updateRibbedStyleUI();}else $id('itemStyleArea').hidden=true;
  const back=$id('itemBackLink');if(back){back.href=currentItem.category==='ribbed'?`ribbed.html?style=${selectedRibbedStyle}`:currentItem.category==='tops'?'tops.html':currentItem.category==='sets'?'sets.html':BFCatalog.categoryUrl(categoryInfo);back.innerHTML=`<i class="fa-solid fa-arrow-left"></i> Back to ${esc(categoryInfo?.name||'collection')}`;}
  updateBuy();
}
function updateBuy(){const price=BFCatalog.price(currentItem,currentSettings),btn=$id('itemAdd');$id('qtyValue').textContent=qty;if(!btn)return;const preorder=itemIsPreorder(),p=activeProduct(),noStock=!preorder&&BFCatalog.stock(currentItem,selectedSize,hasColorVariants()?selectedVariantId:'')<=0;btn.textContent=itemHasSizes()&&!selectedSize?'Choose a size':price?`Add to Bag · ${BF.money(price*qty)}`:'Add to Bag';btn.disabled=p.available===false||(!preorder&&noStock)||(itemHasSizes()&&!selectedSize);}
async function initItem(){
  const params=new URLSearchParams(location.search),id=params.get('id');selectedRibbedStyle=params.get('style')==='twisted'?'twisted':'flat';selectedVariantId=params.get('variant')||'';[allItems,currentSettings,allCategories]=await Promise.all([BFCatalog.load(),BFStore.getDoc('settings/store',{}),BFCatalog.loadCategories()]);currentItem=allItems.find(x=>x.id===id);if(!currentItem||!allCategories.some(c=>c.id===currentItem.category&&c.visible!==false)){location.href='shop.html';return;}
  if(hasColorVariants()){const v=BFCatalog.variant(currentItem,selectedVariantId);selectedVariantId=v.id;}
  let saving=$id('itemSavingNote');if(!saving&&$id('itemPrice')){saving=document.createElement('div');saving.id='itemSavingNote';$id('itemPrice').insertAdjacentElement('afterend',saving);}
  $id('qtyMinus').onclick=()=>{qty=Math.max(1,qty-1);showError();updateBuy();};$id('qtyPlus').onclick=()=>{if(itemHasSizes()&&!selectedSize)return showError('Choose a size first.');const stock=itemStock();if(!itemIsPreorder()&&stock&&qty>=stock)return showError(`Only ${stock} ${stock===1?'piece is':'pieces are'} available right now.`);qty+=1;showError();updateBuy();};$id('itemAdd').onclick=()=>{if(itemHasSizes()&&!selectedSize)return showError('Choose a size first.');const stock=itemStock();if(!itemIsPreorder()){if(stock<=0)return showError('This option is currently sold out.');if(qty>stock)return showError(`Only ${stock} ${stock===1?'piece is':'pieces are'} available right now.`);}else if(activeProduct().available===false)return showError('This option is not available for pre-order.');const p=BFCatalog.price(currentItem,currentSettings);BF.addCatalogProduct(currentItem,selectedSize,p,currentImage(),qty,selectedRibbedStyle,selectedVariantId);qty=1;updateBuy();};
  renderItemView();
}
document.addEventListener('DOMContentLoaded',initItem);
