let currentItem=null,currentSettings={},selectedSize='',qty=1,allItems=[];
const $id=id=>document.getElementById(id);
function showError(msg=''){const el=$id('itemError');if(!el)return;el.textContent=msg;el.hidden=!msg}
function itemStock(){return BFCatalog.stock(currentItem,selectedSize)}
function updateBuy(){const price=BFCatalog.price(currentItem,currentSettings),btn=$id('itemAdd');$id('qtyValue').textContent=qty;if(!btn)return;btn.textContent=currentItem?.sizes&&!selectedSize?'Choose a size':price?`Add to Bag · ${BF.money(price*qty)}`:'Add to Bag';btn.disabled=currentItem?.available===false||!!currentItem?.sizes&&!selectedSize}
async function initItem(){
  const id=new URLSearchParams(location.search).get('id');[allItems,currentSettings]=await Promise.all([BFCatalog.load(),BFStore.getDoc('settings/store',{})]);currentItem=allItems.find(x=>x.id===id);if(!currentItem){location.href='shop.html';return}
  document.title=`${currentItem.name} | Band Factory`;$id('itemName').textContent=currentItem.name;$id('itemCrumb').textContent=currentItem.name;$id('itemDescription').textContent=currentItem.description||'';$id('itemDetailsAccordion').textContent=currentItem.description||'';$id('itemImage').src=BFCatalog.image(currentItem);$id('itemImage').alt=currentItem.name;$id('itemShadeTab').textContent=currentItem.subtitle||currentItem.color||currentItem.name;$id('itemCategory').textContent=currentItem.category==='ribbed'?'Ribbed Hairband':currentItem.category==='tops'?'Band Factory Top':'Band Factory Set';
  const p=BFCatalog.price(currentItem,currentSettings);$id('itemPrice').textContent=p?BF.money(p):'Price available soon';
  const features=(currentItem.subtitle||currentItem.color||'').split('·').map(x=>x.trim()).filter(Boolean).slice(0,4);$id('itemFeatureRow').innerHTML=features.map(x=>`<span>${x}</span>`).join('');
  $id('itemPackNote').innerHTML=currentItem.packSize?`<i class="fa-solid fa-layer-group"></i> ${currentItem.packSize}-piece purchase.`:'';
  if(currentItem.sizes){
    $id('itemSizeArea').hidden=false;$id('itemSizes').innerHTML=Object.entries(currentItem.sizes).map(([size,d])=>`<button class="tube-size-btn" data-size="${size}" ${d.available===false||Number(d.stock)<=0?'disabled':''}>${size}</button>`).join('');
    $id('itemSizes').querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;qty=1;showError();$id('selectedSizeLabel').textContent=`Selected: ${selectedSize}`;$id('itemSizes').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));updateBuy()});
  }
  $id('qtyMinus').onclick=()=>{qty=Math.max(1,qty-1);showError();updateBuy()};$id('qtyPlus').onclick=()=>{if(currentItem.sizes&&!selectedSize)return showError('Choose a size first.');const stock=itemStock();if(stock&&qty>=stock)return showError(`Only ${stock} ${stock===1?'piece is':'pieces are'} available right now.`);qty++;showError();updateBuy()};
  $id('itemAdd').onclick=()=>{if(currentItem.sizes&&!selectedSize)return showError('Choose a size first.');const stock=itemStock();if(stock<=0)return showError('This option is currently sold out.');if(qty>stock)return showError(`Only ${stock} ${stock===1?'piece is':'pieces are'} available right now.`);BF.addCatalogProduct(currentItem,selectedSize,p,BFCatalog.image(currentItem),qty);qty=1;updateBuy()};
  const categoryPage=currentItem.category==='ribbed'?'ribbed.html':currentItem.category==='tops'?'tops.html':'sets.html';const back=$id('itemBackLink');if(back){back.href=categoryPage;back.innerHTML=`<i class="fa-solid fa-arrow-left"></i> Back to ${currentItem.category==='ribbed'?'Ribbed':currentItem.category==='tops'?'Tops':'Sets'}`;}
  const relatedCatalog=['ribbed','tops','sets'].map(cat=>allItems.find(x=>x.category===cat&&x.id!==currentItem.id&&x.available!==false)).filter(Boolean);const smoothRec={name:'Black Smooth Flat Hairband',subtitle:'Smooth Hairband',image:BF.imageForProduct('flat','Black'),url:'product.html?color=Black&style=flat',price:Number(currentSettings.retailPrice||10)};const cards=[smoothRec,...relatedCatalog].slice(0,4);$id('itemRelated').innerHTML=cards.map(item=>{const isSmooth=!!item.url,url=isSmooth?item.url:(item.id==='spandex-tube-top'?'tube-top.html':`item.html?id=${encodeURIComponent(item.id)}`),image=isSmooth?item.image:BFCatalog.image(item),price=isSmooth?item.price:BFCatalog.price(item,currentSettings);return `<a class="catalog-tile" href="${url}"><div class="catalog-tile-media"><img src="${image}" alt="${item.name}" loading="lazy"></div><div class="catalog-tile-copy"><h3>${item.name}</h3><p>${item.subtitle||item.color||''}</p><strong>${price?BF.money(price):'View product'}</strong></div></a>`}).join('');
  updateBuy();
}
document.addEventListener('DOMContentLoaded',initItem);
