let productData={colors:{}},settings={},catalog=BFCatalog.mergeCatalog({}),activeStyle='flat';
const families={All:BF.colors.map(c=>c[0]),Neutrals:['Black','White','Gray','Ash','Nude'],Pinks:['Pink','Peach','Burgundy'],Blues:['Blue Black','Ocean Blue','Baby Blue','Royal Blue'],Browns:['Light Brown','Dark Brown','Chocolate Brown'],Greens:['Mint','Army Green']};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const colorHex=name=>(BF.colors.find(c=>c[0]===name)||['','#ddd'])[1];
function smoothAvailable(c){const d=productData.styles?.[activeStyle]?.colors?.[c]||productData.colors?.[c]||{};const styleOK=activeStyle==='flat'?settings.smoothFlatAvailable!==false:settings.smoothTwistedAvailable!==false;return settings.smoothAvailable!==false&&styleOK&&d.available!==false&&Number(d.stock??1)>0}
function smoothPrice(){return Number(activeStyle==='twisted'?(settings.twistedRetailPrice??settings.retailPrice??10):(settings.retailPrice||10))}
function renderSmooth(list=families.All){const grid=document.getElementById('smoothGrid'),threshold=Number(settings.lowStockThreshold||10),styleName=activeStyle==='flat'?'Flat':'Twisted';grid.innerHTML=list.map(color=>{const d=productData.styles?.[activeStyle]?.colors?.[color]||productData.colors?.[color]||{},ok=smoothAvailable(color),stock=Number(d.stock??0),low=ok&&stock<=threshold;return `<article class="product-card ${ok?'':'is-unavailable'}"><a href="${ok?`product.html?color=${encodeURIComponent(color)}&style=${activeStyle}`:`unavailable.html?color=${encodeURIComponent(color)}&style=${activeStyle}`}"><div class="product-media"><img loading="lazy" src="${BF.imageForProduct(activeStyle,color)}" alt="Smooth ${styleName} Hairband in ${esc(color)}"><span class="style-corner">${ok?(low?'Limited':styleName):'Out of stock'}</span></div></a><div class="product-info"><span class="product-kicker">Smooth Hairbands</span><h3>${styleName} · ${esc(color)}</h3><div class="product-price"><strong>${BF.money(smoothPrice())}</strong><i class="mini-swatch" style="background:${colorHex(color)}"></i></div>${ok?`<button class="catalog-add" onclick="BF.addRetail('${color.replace(/'/g,"\\'")}',1,'${activeStyle}')">Add to bag</button>`:'<small>Currently unavailable</small>'}</div></article>`}).join('')}
function ribbedCard(item,featured=false){const ok=item.available!==false&&Number(item.stock??1)>0;const img=featured?item.image:'images/ribbed-placeholder.svg';const title=featured?item.name:item.name||item.colour;const colour=featured?item.colour:item.colour;return `<article class="product-card ${ok?'':'is-unavailable'}"><div class="product-media ribbed-media"><img loading="lazy" src="${img}" alt="${esc(title)} ribbed hairband"><span class="style-corner">${featured?'Print':'Ribbed'}</span></div><div class="product-info"><span class="product-kicker">Ribbed Hairbands</span><h3>${esc(title)}</h3><p>${esc(featured?item.description:colour)}</p><div class="product-price"><strong>${BF.money(catalog.ribbed.price)}</strong></div>${ok?`<button class="catalog-add" data-ribbed-id="${esc(featured?item.id:colour)}" data-ribbed-featured="${featured}">Add to bag</button>`:'<small>Currently unavailable</small>'}</div></article>`}
function renderRibbed(){const grid=document.getElementById('ribbedGrid');const featured=(catalog.ribbed.featured||[]).map(x=>ribbedCard(x,true));const colours=Object.entries(catalog.ribbed.colours||{}).map(([colour,d])=>ribbedCard({name:colour,colour,...d},false));grid.innerHTML=[...featured,...colours].join('');grid.querySelectorAll('[data-ribbed-id]').forEach(b=>b.onclick=()=>{const featured=b.dataset.ribbedFeatured==='true',key=b.dataset.ribbedId,item=featured?(catalog.ribbed.featured||[]).find(x=>x.id===key):{name:key,colour:key,image:'images/ribbed-placeholder.svg'};BF.addCatalog({productId:featured?item.id:`ribbed-${key.toLowerCase().replace(/\s+/g,'-')}`,name:featured?item.name:`Ribbed Hairband · ${key}`,category:'Hairbands · Ribbed',variant:featured?item.colour:key,price:Number(catalog.ribbed.price),image:item.image||'images/ribbed-placeholder.svg',stockKey:featured?`ribbed.featured.${item.id}`:`ribbed.colours.${key}`})})}
function basicCard(p,group){const sizes=Object.keys(p.sizes||{}),hasSizes=sizes.length>0;return `<article class="basic-card" id="${esc(p.id)}"><div class="basic-image"><img src="${esc(p.image||'images/sets.jpg')}" alt="${esc(p.name)}" loading="lazy"><span>${group==='tops'?'Top':'Set'}</span></div><div class="basic-copy"><span class="product-kicker">Basics · ${group==='tops'?'Tops':'Sets'}</span><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><div class="basic-meta"><span>${esc((p.colours||[]).join(' · '))}</span><span>${esc(p.unitLabel||'')}</span></div>${hasSizes?`<label class="size-label">Size<select data-basic-size="${esc(p.id)}"><option value="">Choose size</option>${sizes.map(s=>`<option value="${esc(s)}" ${p.sizes[s]?.available===false||Number(p.sizes[s]?.stock??0)<=0?'disabled':''}>${esc(s)}</option>`).join('')}</select></label>`:''}<div class="basic-buy"><strong>${BF.money(p.price)}</strong><button class="catalog-add" data-basic-add="${esc(p.id)}" data-group="${group}">Add to bag</button></div><p class="stock-note" data-stock-note="${esc(p.id)}"></p></div></article>`}
function renderBasics(){for(const group of ['tops','sets']){const el=document.getElementById(group==='tops'?'topsGrid':'setsGrid');el.innerHTML=(catalog.basics[group]||[]).map(p=>basicCard(p,group)).join('')}document.querySelectorAll('[data-basic-add]').forEach(btn=>btn.onclick=()=>{const p=BFCatalog.findBasic(catalog,btn.dataset.basicAdd),select=document.querySelector(`[data-basic-size="${p.id}"]`),size=select?.value||'';if(Object.keys(p.sizes||{}).length&&!size)return BF.toast('Choose a size first.');const sizeData=p.sizes?.[size];BF.addCatalog({productId:p.id,name:p.name,category:`Basics · ${btn.dataset.group==='tops'?'Tops':'Sets'}`,variant:[(p.colours||[]).join(', '),size?`Size ${size}`:'',p.unitLabel].filter(Boolean).join(' · '),size,price:Number(p.price),image:p.image,stockKey:size?`basics.${btn.dataset.group}.${p.id}.sizes.${size}`:`basics.${btn.dataset.group}.${p.id}`})})}
function setStyle(style){activeStyle=style;document.querySelectorAll('.style-btn').forEach(b=>b.classList.toggle('active',b.dataset.style===style));renderSmooth(families[document.querySelector('.family-btn.active')?.dataset.family||'All'])}
async function initShop(){[settings,productData,catalog]=await Promise.all([BFStore.getDoc('settings/store',{}),BFStore.getDoc('products/smooth',{colors:{}}),BFStore.getDoc('products/catalog',{}).then(BFCatalog.mergeCatalog)]);BF.settings={...BF.settings,...settings};renderSmooth();renderRibbed();renderBasics();document.querySelectorAll('.style-btn').forEach(b=>b.onclick=()=>setStyle(b.dataset.style));document.querySelectorAll('.family-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.family-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSmooth(families[b.dataset.family]||families.All)});const params=new URLSearchParams(location.search);const section=params.get('section');if(section)document.getElementById(section)?.scrollIntoView({block:'start'})}
document.addEventListener('DOMContentLoaded',initShop);
