(function(){
 const statuses=['Preparing','Ready','Dispatched','Delivered'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const money=v=>`GHS ${Number(v||0).toLocaleString('en-GH',{maximumFractionDigits:2})}`;
 const date=v=>{const d=new Date(v||'');return Number.isNaN(d.getTime())?'To be confirmed':new Intl.DateTimeFormat('en-GH',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(d)};
 async function lookup(payload){const r=await fetch('/.netlify/functions/track-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),x=await r.json().catch(()=>({}));if(!r.ok||!x.ok)throw new Error(x.error||'We could not find that order.');return x}
 function mount(){
   if(document.getElementById('bfTrackScreen')||document.body.classList.contains('admin-body'))return;
   document.body.insertAdjacentHTML('beforeend',`<button class="bf-track-launch" type="button" data-bf-track-open><i class="fa-solid fa-location-dot" aria-hidden="true"></i><span>Track order</span></button><div class="bf-track-screen" id="bfTrackScreen" aria-hidden="true"><aside class="bf-track-drawer" role="dialog" aria-modal="true" aria-labelledby="bfTrackTitle"><div class="bf-track-head"><div class="bf-track-brand">BΛND FΛCTORY · TRACKING</div><button class="bf-track-close" type="button" data-bf-track-close aria-label="Close order tracking">×</button></div><div class="bf-track-body"><div class="bf-track-kicker">No account needed</div><h2 class="bf-track-title" id="bfTrackTitle">Where’s my order?</h2><p class="bf-track-copy">Enter the order number from your confirmation and the email used at checkout. Don’t have access to that email? You can switch to your checkout phone number.</p><form class="bf-track-form" id="bfTrackForm"><div class="bf-track-field"><label for="bfTrackOrder">Order number</label><input id="bfTrackOrder" name="orderId" autocomplete="off" placeholder="BF-00001" required></div><div class="bf-track-field" id="bfTrackEmailWrap"><label for="bfTrackEmail">Checkout email</label><input id="bfTrackEmail" name="email" type="email" autocomplete="email" placeholder="you@example.com" required></div><div class="bf-track-field" id="bfTrackPhoneWrap" hidden><label for="bfTrackPhone">Checkout phone number</label><input id="bfTrackPhone" name="phone" type="tel" autocomplete="tel" placeholder="e.g. 050 000 0000"></div><button class="bf-track-alt" type="button" id="bfTrackAlt">I can’t use that email — use my phone number instead</button><button class="bf-track-submit" type="submit">Find my order</button><div class="bf-track-note" id="bfTrackNote" aria-live="polite"></div></form><div class="bf-track-result" id="bfTrackResult" hidden></div></div></aside></div>`);
   const screen=document.getElementById('bfTrackScreen'),form=document.getElementById('bfTrackForm'),note=document.getElementById('bfTrackNote'),result=document.getElementById('bfTrackResult'),alt=document.getElementById('bfTrackAlt'),emailWrap=document.getElementById('bfTrackEmailWrap'),phoneWrap=document.getElementById('bfTrackPhoneWrap'),email=document.getElementById('bfTrackEmail'),phone=document.getElementById('bfTrackPhone');let phoneMode=false;
   const open=()=>{screen.classList.add('is-open');screen.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>document.getElementById('bfTrackOrder')?.focus(),160)};
   const close=()=>{screen.classList.remove('is-open');screen.setAttribute('aria-hidden','true');document.body.style.overflow=''};
   document.querySelectorAll('[data-bf-track-open]').forEach(b=>b.addEventListener('click',open));screen.querySelector('[data-bf-track-close]').onclick=close;screen.addEventListener('click',e=>{if(e.target===screen)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&screen.classList.contains('is-open'))close()});
   alt.onclick=()=>{phoneMode=!phoneMode;emailWrap.hidden=phoneMode;phoneWrap.hidden=!phoneMode;email.required=!phoneMode;phone.required=phoneMode;alt.textContent=phoneMode?'Use my checkout email instead':'I can’t use that email — use my phone number instead';(phoneMode?phone:email).focus()};
   form.onsubmit=async e=>{e.preventDefault();note.textContent='';result.hidden=true;const btn=form.querySelector('.bf-track-submit');btn.disabled=true;btn.textContent='Looking it up…';try{const fd=new FormData(form),data=await lookup({orderId:fd.get('orderId'),email:phoneMode?'':fd.get('email'),phone:phoneMode?fd.get('phone'):''});render(data.order,data.token,result);result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',`${location.pathname}${location.search.replace(/([?&])track=[^&]*&?/,'$1').replace(/[?&]$/,'')}`)}catch(err){note.textContent=err.message}finally{btn.disabled=false;btn.textContent='Find my order'}};
   const token=new URLSearchParams(location.search).get('track');if(token){open();note.textContent='Opening your order…';lookup({token}).then(data=>{render(data.order,data.token,result);result.hidden=false;note.textContent=''}).catch(err=>note.textContent=err.message)}
 }
 function render(o,token,target){
   const idx=statuses.indexOf(o.status),cancelled=o.status==='Cancelled';const steps=statuses.map((s,i)=>`<div class="bf-track-step ${!cancelled&&i<idx?'done':!cancelled&&i===idx?'current':''}">${esc(s)}</div>`).join('');const when=o.fulfilment==='pickup'?(o.pickupDate?date(o.pickupDate):'To be confirmed'):(o.fulfilmentDate?date(o.fulfilmentDate):'To be confirmed');const location=o.fulfilment==='pickup'?(o.pickupAddress||'Pickup location to be confirmed'):[o.city,o.region,o.country].filter(Boolean).join(', ')||'Delivery details saved';const items=(o.items||[]).map(i=>`<div class="bf-track-item"><div><div class="bf-track-item-name">${esc(i.name)}</div><div class="bf-track-item-meta">${esc([i.color,i.size,i.style,i.qty>1?`Qty ${i.qty}`:''].filter(Boolean).join(' · '))}</div></div><div class="bf-track-item-price">${money(Number(i.price||0)*Number(i.qty||1))}</div></div>`).join('');
   target.innerHTML=`<section class="bf-track-hero"><small>${esc(o.id)}</small><h3>${cancelled?'This order was cancelled.':o.status==='Delivered'?'Delivered. Looks good from here ♡':o.status==='Dispatched'?'Your order is on the move.':o.status==='Ready'?'Packed and ready for what’s next.':'Your order is in the works.'}</h3><p>Placed ${date(o.createdAt)} · ${esc(o.fulfilment||'Order')} order</p><span class="bf-track-status-pill">${esc(o.status)}</span></section>${cancelled?'<div class="bf-track-cancelled">If this cancellation looks unexpected, contact Band Factory and include your order number so we can help.</div>':`<div class="bf-track-timeline">${steps}</div>`}<section class="bf-track-card"><div class="bf-track-card-title">Fulfilment</div><div class="bf-track-grid"><div class="bf-track-meta"><span>Method</span><strong>${esc(o.fulfilment||'Delivery')}</strong></div><div class="bf-track-meta"><span>${o.fulfilment==='pickup'?'Pickup date':'Dispatch / fulfilment date'}</span><strong>${esc(when)}</strong></div><div class="bf-track-meta"><span>Destination</span><strong>${esc(location)}</strong></div><div class="bf-track-meta"><span>Payment</span><strong>${esc(o.payment||'Paid')}</strong></div></div></section><section class="bf-track-card"><div class="bf-track-card-title">Order summary</div>${items||'<div class="bf-track-item-name">Your items are saved with this order.</div>'}<div class="bf-track-total"><span>Order total</span><span>${money(o.total)}</span></div>${o.deliveryFeeStatus?`<div class="bf-track-item-meta" style="margin-top:9px">Delivery fee: ${esc(o.deliveryFeeStatus)}</div>`:''}</section>`;
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
