const TUBE_TOP_DEFAULT={name:'Spandex Tube Top',price:64,color:'Black',sizes:{XS:{stock:3,available:true},S:{stock:4,available:true},M:{stock:3,available:true},L:{stock:3,available:true},XL:{stock:3,available:true},'2XL':{stock:3,available:true}}};
let tubeTop=TUBE_TOP_DEFAULT,selectedTubeSize='',tubeQty=1;
const sizeOrder=['S','L','M','XL','2XL','XS','3XL','4XL','5XL','6XL'];
function availableTubeSizes(){const keys=Object.keys(tubeTop?.sizes||{});return keys.sort((a,b)=>{const ai=sizeOrder.indexOf(a.toUpperCase()),bi=sizeOrder.indexOf(b.toUpperCase());return (ai<0?1000:ai)-(bi<0?1000:bi)||a.localeCompare(b,undefined,{numeric:true})})}
function sizeStock(size){const d=tubeTop?.sizes?.[size]||{};return d.available===false?0:Math.max(0,Number(d.stock??0))}
function totalTubeStock(){return availableTubeSizes().reduce((n,size)=>n+sizeStock(size),0)}
function tubeError(message=''){tubeSizeError.textContent=message;tubeSizeError.hidden=!message}
function renderTubeSizes(){const total=totalTubeStock();tubeSizeGrid.innerHTML=availableTubeSizes().map(size=>{const stock=sizeStock(size),sold=stock<=0;return `<button class="tube-size-btn ${selectedTubeSize===size?'active':''}" type="button" data-tube-size="${size}" ${sold?'disabled':''}>${size}${sold?'<small>Sold out</small>':''}</button>`}).join('');tubeSizeGrid.querySelectorAll('[data-tube-size]').forEach(btn=>btn.onclick=()=>{selectedTubeSize=btn.dataset.tubeSize;tubeQty=1;tubeError();renderTubeSizes();updateTubeControls()});tubeStockNotice.textContent=total?'Limited release · Black only':'This limited release is currently sold out.';tubeStockNotice.classList.toggle('tube-sold-out',!total);updateTubeControls()}
function updateTubeControls(){tubeQtyValue.textContent=tubeQty;selectedSizeLabel.textContent=selectedTubeSize?`Black · ${selectedTubeSize}`:'Choose one to continue';const stock=selectedTubeSize?sizeStock(selectedTubeSize):0;tubeAddToBag.disabled=!selectedTubeSize||stock<=0;tubeAddToBag.textContent=selectedTubeSize&&stock>0?`Add to Bag - ${BF.money(Number(tubeTop.price||64)*tubeQty)}`:'Choose a size'}
async function initTubeTop(){tubeTop=await BFStore.getDoc('products/spandexTubeTop',TUBE_TOP_DEFAULT)||TUBE_TOP_DEFAULT;if(document.getElementById('tubePrice'))tubePrice.textContent=BF.money(Number(tubeTop.price||64));if(document.getElementById('tubeDescription'))tubeDescription.textContent=tubeTop.description||'Double lined and stretchy, with a clean black finish that is easy to dress up or keep casual.';renderTubeSizes();tubeQtyMinus.onclick=()=>{tubeQty=Math.max(1,tubeQty-1);tubeError();updateTubeControls()};tubeQtyPlus.onclick=()=>{if(!selectedTubeSize){tubeError('Pick your size first ♡');return}const stock=sizeStock(selectedTubeSize);if(tubeQty>=stock){tubeError(`That's all we've got ✨ Only ${stock} ${selectedTubeSize} ${stock===1?'is':'are'} available right now.`);return}tubeQty++;tubeError();updateTubeControls()};tubeAddToBag.onclick=()=>{if(!selectedTubeSize){tubeError('Pick your size first ♡ Select a size before adding your tube top to your Bag.');return}const stock=sizeStock(selectedTubeSize);if(tubeQty>stock){tubeError(`Only ${stock} ${selectedTubeSize} ${stock===1?'is':'are'} available right now.`);return}BF.addApparel('spandex-tube-top','Spandex Tube Top',selectedTubeSize,Number(tubeTop.price||64),'images/new.jpeg',tubeQty);tubeQty=1;updateTubeControls()};if(document.getElementById('tubeRelated')){const catalogItems=await BFCatalog.load(),settings=await BFStore.getDoc('settings/store',{});const relatedCatalog=['ribbed','tops','sets'].map(cat=>catalogItems.find(x=>x.category===cat&&x.id!=='spandex-tube-top'&&x.available!==false)).filter(Boolean);const smooth={name:'Black Smooth Flat Hairband',subtitle:'Smooth Hairband',image:BF.imageForProduct('flat','Black'),url:'product.html?color=Black&style=flat',price:Number(settings.retailPrice||10)};const related=[smooth,...relatedCatalog].slice(0,4);tubeRelated.innerHTML=related.map(item=>{const url=item.url||`item.html?id=${encodeURIComponent(item.id)}`,image=item.image||BFCatalog.image(item),price=item.price||BFCatalog.price(item,settings);return `<a class="catalog-tile" href="${url}"><div class="catalog-tile-media"><img src="${image}" alt="${item.name}" loading="lazy"></div><div class="catalog-tile-copy"><h3>${item.name}</h3><p>${item.subtitle||item.color||''}</p><strong>${price?BF.money(price):'View product'}</strong></div></a>`}).join('');}
const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:'Spandex Tube Top',image:['https://bandfactory.store/images/new.jpeg'],description:tubeTop.description||'Double lined and stretchy black Spandex Tube Top.',brand:{'@type':'Brand',name:'Band Factory'},offers:{'@type':'Offer',url:'https://bandfactory.store/tube-top.html',priceCurrency:'GHS',price:Number(tubeTop.price||64).toFixed(2),availability:totalTubeStock()>0?'https://schema.org/InStock':'https://schema.org/OutOfStock'}});document.head.appendChild(schema)}
document.addEventListener('DOMContentLoaded',initTubeTop);