const TUBE_TOP_DEFAULT={name:'Spandex Tube Top',price:64,color:'Black',sizes:{XS:{stock:3,available:true},S:{stock:4,available:true},M:{stock:3,available:true},L:{stock:3,available:true},XL:{stock:3,available:true},'2XL':{stock:3,available:true}}};
let tubeTop=TUBE_TOP_DEFAULT,selectedTubeSize='',tubeQty=1;
const sizeOrder=['XS','S','M','L','XL','2XL'];
function sizeStock(size){const d=tubeTop?.sizes?.[size]||{};return d.available===false?0:Math.max(0,Number(d.stock??0))}
function totalTubeStock(){return sizeOrder.reduce((n,size)=>n+sizeStock(size),0)}
function tubeError(message=''){tubeSizeError.textContent=message;tubeSizeError.hidden=!message}
function renderTubeSizes(){const total=totalTubeStock();tubeSizeGrid.innerHTML=sizeOrder.map(size=>{const stock=sizeStock(size),sold=stock<=0;return `<button class="tube-size-btn ${selectedTubeSize===size?'active':''}" type="button" data-tube-size="${size}" ${sold?'disabled':''}>${size}${sold?'<small>Sold out</small>':''}</button>`}).join('');tubeSizeGrid.querySelectorAll('[data-tube-size]').forEach(btn=>btn.onclick=()=>{selectedTubeSize=btn.dataset.tubeSize;tubeQty=1;tubeError();renderTubeSizes();updateTubeControls()});tubeStockNotice.textContent=total?'Limited release · Black only':'This limited release is currently sold out.';tubeStockNotice.classList.toggle('tube-sold-out',!total);updateTubeControls()}
function updateTubeControls(){tubeQtyValue.textContent=tubeQty;selectedSizeLabel.textContent=selectedTubeSize?`Black · ${selectedTubeSize}`:'Choose one to continue';const stock=selectedTubeSize?sizeStock(selectedTubeSize):0;tubeAddToBag.disabled=!selectedTubeSize||stock<=0;tubeAddToBag.textContent=selectedTubeSize&&stock>0?`Add to Bag — ${BF.money(Number(tubeTop.price||64)*tubeQty)}`:'Choose a size'}
async function initTubeTop(){tubeTop=await BFStore.getDoc('products/spandexTubeTop',TUBE_TOP_DEFAULT)||TUBE_TOP_DEFAULT;renderTubeSizes();tubeQtyMinus.onclick=()=>{tubeQty=Math.max(1,tubeQty-1);tubeError();updateTubeControls()};tubeQtyPlus.onclick=()=>{if(!selectedTubeSize){tubeError('Pick your size first ♡');return}const stock=sizeStock(selectedTubeSize);if(tubeQty>=stock){tubeError(`That's all we've got ✨ Only ${stock} ${selectedTubeSize} ${stock===1?'is':'are'} available right now.`);return}tubeQty++;tubeError();updateTubeControls()};tubeAddToBag.onclick=()=>{if(!selectedTubeSize){tubeError('Pick your size first ♡ Select a size before adding your tube top to your Bag.');return}const stock=sizeStock(selectedTubeSize);if(tubeQty>stock){tubeError(`Only ${stock} ${selectedTubeSize} ${stock===1?'is':'are'} available right now.`);return}BF.addApparel('spandex-tube-top','Spandex Tube Top',selectedTubeSize,Number(tubeTop.price||64),'images/new.jpeg',tubeQty);tubeQty=1;updateTubeControls()};const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:'Spandex Tube Top',image:['https://bandfactory.store/images/new.jpeg'],description:'Double lined and stretchy black Spandex Tube Top.',brand:{'@type':'Brand',name:'Band Factory'},offers:{'@type':'Offer',url:'https://bandfactory.store/tube-top.html',priceCurrency:'GHS',price:'64.00',availability:totalTubeStock()>0?'https://schema.org/InStock':'https://schema.org/OutOfStock'}});document.head.appendChild(schema)}
document.addEventListener('DOMContentLoaded',initTubeTop);